name: group_chat
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    responsive_builder: ^0.1.4
    provider: ^4.0.1
    logger: ^0.7.0+2
    get_it: ^3.0.3
    equatable: ^2.0.0
    provider_architecture: ^1.1.1+1
    # firebase_core: ^1.0.2
    flutter_login: ^1.0.15
    progress_state_button: ^1.0.2
    flutter_signin_button: ^1.1.0
    email_validator: '^1.0.0'
    bottom_navy_bar: ^6.0.0
    animated_bottom_navigation_bar: ^0.3.2
    expandable_sliver_list: ^4.0.0
    font_awesome_flutter: ^8.2.0
    faker: ^1.3.0
    google_maps_flutter: ^2.0.3
    geolocator: ^7.0.2
    dio: ^4.0.0
    sqflite: ^1.3.0
    path_provider: ^2.0.1
    intl: ^0.17.0
    scrollable_positioned_list: ^0.2.3
    after_layout: ^1.1.0
    firebase_messaging: ^11.2.8
    flutter_local_notifications: ^9.3.3
    firebase_core: ^1.14.0
    imei_plugin: ^1.2.0
dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true
    assets:
        - assets/images/welcome_image.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
